/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DeskGW {
  export type JobStruct = {
    status: BigNumberish;
    client: AddressLike;
    hMat: BytesLike;
    pkC: BytesLike;
    cidMat: BytesLike;
    capV: BytesLike;
    dep: BigNumberish;
    due: BigNumberish;
    claimUntil: BigNumberish;
    claimer: AddressLike;
    cidOut: BytesLike;
    hRes: BytesLike;
    pkDj: BytesLike;
    provider: AddressLike;
  };

  export type JobStructOutput = [
    status: bigint,
    client: string,
    hMat: string,
    pkC: string,
    cidMat: string,
    capV: string,
    dep: bigint,
    due: bigint,
    claimUntil: bigint,
    claimer: string,
    cidOut: string,
    hRes: string,
    pkDj: string,
    provider: string
  ] & {
    status: bigint;
    client: string;
    hMat: string;
    pkC: string;
    cidMat: string;
    capV: string;
    dep: bigint;
    due: bigint;
    claimUntil: bigint;
    claimer: string;
    cidOut: string;
    hRes: string;
    pkDj: string;
    provider: string;
  };
}

export interface DeskGWInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowlisted"
      | "claimTTL"
      | "getJob"
      | "org"
      | "pinService"
      | "pinned"
      | "postClaim"
      | "postCmp"
      | "postReq"
      | "providerCount"
      | "providerList"
      | "registerProvider"
      | "serviceFee"
      | "sid"
      | "timeoutRefund"
      | "vkZK"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimPosted"
      | "CmpAccepted"
      | "ProviderRegistered"
      | "ReqPosted"
      | "ServicePinned"
      | "TimeoutRefund"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowlisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claimTTL", values?: undefined): string;
  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "org", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pinService",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pinned", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postClaim",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postCmp",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "postReq",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "providerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serviceFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeoutRefund",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vkZK", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "allowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTTL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "org", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pinService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pinned", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postCmp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postReq", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "providerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "serviceFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeoutRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vkZK", data: BytesLike): Result;
}

export namespace ClaimPostedEvent {
  export type InputTuple = [
    jid: BytesLike,
    provider: AddressLike,
    claimUntil: BigNumberish
  ];
  export type OutputTuple = [jid: string, provider: string, claimUntil: bigint];
  export interface OutputObject {
    jid: string;
    provider: string;
    claimUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CmpAcceptedEvent {
  export type InputTuple = [
    jid: BytesLike,
    provider: AddressLike,
    cidOut: BytesLike,
    hRes: BytesLike
  ];
  export type OutputTuple = [
    jid: string,
    provider: string,
    cidOut: string,
    hRes: string
  ];
  export interface OutputObject {
    jid: string;
    provider: string;
    cidOut: string;
    hRes: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReqPostedEvent {
  export type InputTuple = [
    jid: BytesLike,
    sid: BytesLike,
    client: AddressLike,
    cidMat: BytesLike,
    dep: BigNumberish,
    due: BigNumberish
  ];
  export type OutputTuple = [
    jid: string,
    sid: string,
    client: string,
    cidMat: string,
    dep: bigint,
    due: bigint
  ];
  export interface OutputObject {
    jid: string;
    sid: string;
    client: string;
    cidMat: string;
    dep: bigint;
    due: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServicePinnedEvent {
  export type InputTuple = [sid: BytesLike];
  export type OutputTuple = [sid: string];
  export interface OutputObject {
    sid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutRefundEvent {
  export type InputTuple = [jid: BytesLike, refundAddr: AddressLike];
  export type OutputTuple = [jid: string, refundAddr: string];
  export interface OutputObject {
    jid: string;
    refundAddr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeskGW extends BaseContract {
  connect(runner?: ContractRunner | null): DeskGW;
  waitForDeployment(): Promise<this>;

  interface: DeskGWInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowlisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  claimTTL: TypedContractMethod<[], [bigint], "view">;

  getJob: TypedContractMethod<
    [jid: BytesLike],
    [DeskGW.JobStructOutput],
    "view"
  >;

  org: TypedContractMethod<[], [string], "view">;

  pinService: TypedContractMethod<
    [
      _sid: BytesLike,
      _vkZK: BytesLike,
      _claimTTL: BigNumberish,
      _serviceFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  pinned: TypedContractMethod<[], [boolean], "view">;

  postClaim: TypedContractMethod<
    [jid: BytesLike, comJ: BytesLike, claimWindow: BigNumberish],
    [void],
    "nonpayable"
  >;

  postCmp: TypedContractMethod<
    [
      jid: BytesLike,
      cidOut: BytesLike,
      hRes: BytesLike,
      pi: BytesLike,
      pkDj: BytesLike,
      sigJ: BytesLike,
      j: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  postReq: TypedContractMethod<
    [
      jid: BytesLike,
      hMat: BytesLike,
      pkC: BytesLike,
      cidMat: BytesLike,
      capV: BytesLike,
      due: BigNumberish
    ],
    [void],
    "payable"
  >;

  providerCount: TypedContractMethod<[], [bigint], "view">;

  providerList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  registerProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  serviceFee: TypedContractMethod<[], [bigint], "view">;

  sid: TypedContractMethod<[], [string], "view">;

  timeoutRefund: TypedContractMethod<
    [jid: BytesLike, refundAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  vkZK: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowlisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimTTL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<[jid: BytesLike], [DeskGW.JobStructOutput], "view">;
  getFunction(
    nameOrSignature: "org"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pinService"
  ): TypedContractMethod<
    [
      _sid: BytesLike,
      _vkZK: BytesLike,
      _claimTTL: BigNumberish,
      _serviceFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pinned"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "postClaim"
  ): TypedContractMethod<
    [jid: BytesLike, comJ: BytesLike, claimWindow: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "postCmp"
  ): TypedContractMethod<
    [
      jid: BytesLike,
      cidOut: BytesLike,
      hRes: BytesLike,
      pi: BytesLike,
      pkDj: BytesLike,
      sigJ: BytesLike,
      j: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "postReq"
  ): TypedContractMethod<
    [
      jid: BytesLike,
      hMat: BytesLike,
      pkC: BytesLike,
      cidMat: BytesLike,
      capV: BytesLike,
      due: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "providerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "providerList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "serviceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sid"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timeoutRefund"
  ): TypedContractMethod<
    [jid: BytesLike, refundAddr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vkZK"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ClaimPosted"
  ): TypedContractEvent<
    ClaimPostedEvent.InputTuple,
    ClaimPostedEvent.OutputTuple,
    ClaimPostedEvent.OutputObject
  >;
  getEvent(
    key: "CmpAccepted"
  ): TypedContractEvent<
    CmpAcceptedEvent.InputTuple,
    CmpAcceptedEvent.OutputTuple,
    CmpAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ReqPosted"
  ): TypedContractEvent<
    ReqPostedEvent.InputTuple,
    ReqPostedEvent.OutputTuple,
    ReqPostedEvent.OutputObject
  >;
  getEvent(
    key: "ServicePinned"
  ): TypedContractEvent<
    ServicePinnedEvent.InputTuple,
    ServicePinnedEvent.OutputTuple,
    ServicePinnedEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutRefund"
  ): TypedContractEvent<
    TimeoutRefundEvent.InputTuple,
    TimeoutRefundEvent.OutputTuple,
    TimeoutRefundEvent.OutputObject
  >;

  filters: {
    "ClaimPosted(bytes32,address,uint64)": TypedContractEvent<
      ClaimPostedEvent.InputTuple,
      ClaimPostedEvent.OutputTuple,
      ClaimPostedEvent.OutputObject
    >;
    ClaimPosted: TypedContractEvent<
      ClaimPostedEvent.InputTuple,
      ClaimPostedEvent.OutputTuple,
      ClaimPostedEvent.OutputObject
    >;

    "CmpAccepted(bytes32,address,bytes32,bytes32)": TypedContractEvent<
      CmpAcceptedEvent.InputTuple,
      CmpAcceptedEvent.OutputTuple,
      CmpAcceptedEvent.OutputObject
    >;
    CmpAccepted: TypedContractEvent<
      CmpAcceptedEvent.InputTuple,
      CmpAcceptedEvent.OutputTuple,
      CmpAcceptedEvent.OutputObject
    >;

    "ProviderRegistered(address)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;

    "ReqPosted(bytes32,bytes32,address,bytes32,uint256,uint64)": TypedContractEvent<
      ReqPostedEvent.InputTuple,
      ReqPostedEvent.OutputTuple,
      ReqPostedEvent.OutputObject
    >;
    ReqPosted: TypedContractEvent<
      ReqPostedEvent.InputTuple,
      ReqPostedEvent.OutputTuple,
      ReqPostedEvent.OutputObject
    >;

    "ServicePinned(bytes32)": TypedContractEvent<
      ServicePinnedEvent.InputTuple,
      ServicePinnedEvent.OutputTuple,
      ServicePinnedEvent.OutputObject
    >;
    ServicePinned: TypedContractEvent<
      ServicePinnedEvent.InputTuple,
      ServicePinnedEvent.OutputTuple,
      ServicePinnedEvent.OutputObject
    >;

    "TimeoutRefund(bytes32,address)": TypedContractEvent<
      TimeoutRefundEvent.InputTuple,
      TimeoutRefundEvent.OutputTuple,
      TimeoutRefundEvent.OutputObject
    >;
    TimeoutRefund: TypedContractEvent<
      TimeoutRefundEvent.InputTuple,
      TimeoutRefundEvent.OutputTuple,
      TimeoutRefundEvent.OutputObject
    >;
  };
}
