/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DeskGWInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addProvider"
      | "allowedProviders"
      | "claim"
      | "claimWindow"
      | "complete"
      | "completionWindow"
      | "getRequest"
      | "owner"
      | "removeProvider"
      | "request"
      | "requests"
      | "serviceDescHash"
      | "serviceFee"
      | "timeout"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProviderAdded"
      | "ProviderRemoved"
      | "RequestClaimed"
      | "RequestCompleted"
      | "RequestOpened"
      | "RequestRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "complete",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completionWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "request",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "requests", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "serviceDescHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serviceFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timeout", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "addProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "complete", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completionWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "request", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "serviceDescHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "serviceFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timeout", data: BytesLike): Result;
}

export namespace ProviderAddedEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRemovedEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestClaimedEvent {
  export type InputTuple = [requestId: BytesLike, provider: AddressLike];
  export type OutputTuple = [requestId: string, provider: string];
  export interface OutputObject {
    requestId: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCompletedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    resultCid: BytesLike,
    provider: AddressLike
  ];
  export type OutputTuple = [
    requestId: string,
    resultCid: string,
    provider: string
  ];
  export interface OutputObject {
    requestId: string;
    resultCid: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestOpenedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    payloadCid: BytesLike,
    client: AddressLike,
    escrow: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    payloadCid: string,
    client: string,
    escrow: bigint
  ];
  export interface OutputObject {
    requestId: string;
    payloadCid: string;
    client: string;
    escrow: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRefundedEvent {
  export type InputTuple = [requestId: BytesLike, client: AddressLike];
  export type OutputTuple = [requestId: string, client: string];
  export interface OutputObject {
    requestId: string;
    client: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeskGW extends BaseContract {
  connect(runner?: ContractRunner | null): DeskGW;
  waitForDeployment(): Promise<this>;

  interface: DeskGWInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  allowedProviders: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  claim: TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;

  claimWindow: TypedContractMethod<[], [bigint], "view">;

  complete: TypedContractMethod<
    [requestId: BytesLike, resultCid: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  completionWindow: TypedContractMethod<[], [bigint], "view">;

  getRequest: TypedContractMethod<
    [requestId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        payloadCid: string;
        client: string;
        escrow: bigint;
        openedAt: bigint;
        claimedAt: bigint;
        provider: string;
        resultCid: string;
        completionProof: string;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  request: TypedContractMethod<
    [requestId: BytesLike, payloadCid: BytesLike],
    [void],
    "payable"
  >;

  requests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        payloadCid: string;
        client: string;
        escrow: bigint;
        openedAt: bigint;
        claimedAt: bigint;
        provider: string;
        resultCid: string;
        completionProof: string;
        status: bigint;
      }
    ],
    "view"
  >;

  serviceDescHash: TypedContractMethod<[], [string], "view">;

  serviceFee: TypedContractMethod<[], [bigint], "view">;

  timeout: TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowedProviders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "complete"
  ): TypedContractMethod<
    [requestId: BytesLike, resultCid: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completionWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        payloadCid: string;
        client: string;
        escrow: bigint;
        openedAt: bigint;
        claimedAt: bigint;
        provider: string;
        resultCid: string;
        completionProof: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "request"
  ): TypedContractMethod<
    [requestId: BytesLike, payloadCid: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        payloadCid: string;
        client: string;
        escrow: bigint;
        openedAt: bigint;
        claimedAt: bigint;
        provider: string;
        resultCid: string;
        completionProof: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "serviceDescHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "serviceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timeout"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "ProviderAdded"
  ): TypedContractEvent<
    ProviderAddedEvent.InputTuple,
    ProviderAddedEvent.OutputTuple,
    ProviderAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRemoved"
  ): TypedContractEvent<
    ProviderRemovedEvent.InputTuple,
    ProviderRemovedEvent.OutputTuple,
    ProviderRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestClaimed"
  ): TypedContractEvent<
    RequestClaimedEvent.InputTuple,
    RequestClaimedEvent.OutputTuple,
    RequestClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCompleted"
  ): TypedContractEvent<
    RequestCompletedEvent.InputTuple,
    RequestCompletedEvent.OutputTuple,
    RequestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RequestOpened"
  ): TypedContractEvent<
    RequestOpenedEvent.InputTuple,
    RequestOpenedEvent.OutputTuple,
    RequestOpenedEvent.OutputObject
  >;
  getEvent(
    key: "RequestRefunded"
  ): TypedContractEvent<
    RequestRefundedEvent.InputTuple,
    RequestRefundedEvent.OutputTuple,
    RequestRefundedEvent.OutputObject
  >;

  filters: {
    "ProviderAdded(address)": TypedContractEvent<
      ProviderAddedEvent.InputTuple,
      ProviderAddedEvent.OutputTuple,
      ProviderAddedEvent.OutputObject
    >;
    ProviderAdded: TypedContractEvent<
      ProviderAddedEvent.InputTuple,
      ProviderAddedEvent.OutputTuple,
      ProviderAddedEvent.OutputObject
    >;

    "ProviderRemoved(address)": TypedContractEvent<
      ProviderRemovedEvent.InputTuple,
      ProviderRemovedEvent.OutputTuple,
      ProviderRemovedEvent.OutputObject
    >;
    ProviderRemoved: TypedContractEvent<
      ProviderRemovedEvent.InputTuple,
      ProviderRemovedEvent.OutputTuple,
      ProviderRemovedEvent.OutputObject
    >;

    "RequestClaimed(bytes32,address)": TypedContractEvent<
      RequestClaimedEvent.InputTuple,
      RequestClaimedEvent.OutputTuple,
      RequestClaimedEvent.OutputObject
    >;
    RequestClaimed: TypedContractEvent<
      RequestClaimedEvent.InputTuple,
      RequestClaimedEvent.OutputTuple,
      RequestClaimedEvent.OutputObject
    >;

    "RequestCompleted(bytes32,bytes32,address)": TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;
    RequestCompleted: TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;

    "RequestOpened(bytes32,bytes32,address,uint256)": TypedContractEvent<
      RequestOpenedEvent.InputTuple,
      RequestOpenedEvent.OutputTuple,
      RequestOpenedEvent.OutputObject
    >;
    RequestOpened: TypedContractEvent<
      RequestOpenedEvent.InputTuple,
      RequestOpenedEvent.OutputTuple,
      RequestOpenedEvent.OutputObject
    >;

    "RequestRefunded(bytes32,address)": TypedContractEvent<
      RequestRefundedEvent.InputTuple,
      RequestRefundedEvent.OutputTuple,
      RequestRefundedEvent.OutputObject
    >;
    RequestRefunded: TypedContractEvent<
      RequestRefundedEvent.InputTuple,
      RequestRefundedEvent.OutputTuple,
      RequestRefundedEvent.OutputObject
    >;
  };
}
