/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DeskGW } from "./DeskGW";
export * as factories from "./factories";
export { DeskGW__factory } from "./factories/DeskGW__factory";
